[workspace]
authors = ["Cade Mirchandani <cmirchan@ucsc.edu>"]
channels = ["conda-forge", "bioconda"]
name = "snakemake-profiling"
platforms = ["osx-arm64", "linux-64", "osx-64"]
version = "0.1.0"

[tasks]
profile-simple = { cmd = "pyinstrument -o simple.pyisession -m snakemake -s workflows/simple.smk -d workflows/output --cores all {{ '-n' if dryrun else '' }}", args = [
    { arg = "dryrun", default = "" },
] }
view-profile = { cmd = "pyinstrument -r html --load {{prof}}", args = ["prof"] }
clean = { cmd = "rm -rf ./workflows/output" }

[dependencies]
snakemake = "*"
python = ">=3.13.5,<3.14"
pip = ">=25.2,<26"

[pypi-dependencies]
pyinstrument = ">=5.0.3, <6"
