# Configurable Snakefile for DAG profiling
import time
import random

# Configuration with defaults
config.setdefault("samples", 30)
config.setdefault("multiplier", 1.0)  # Float 0-1 for completion percentage
config.setdefault("reps", 10)
config.setdefault("prefix", "Processed")  # Parameter for testing param changes
SAMPLES = [f"sample{i}" for i in range(config["samples"])]

# Calculate actual reps based on percentage (max 1000 for big workflow)

actual_reps = int(config["reps"] * config["multiplier"])
REPS = range(actual_reps)


rule all:
    input:
        expand("{rep}/results/summary.txt", rep=REPS),


rule process_sample:
    output:
        "{rep}/results/{sample}.processed",
    params:
        prefix=config["prefix"]
    shell:
        "echo 'Processed {wildcards.sample}' > {output}"


rule analyze_sample:
    input:
        "{rep}/results/{sample}.processed",
    output:
        "{rep}/results/{sample}.analyzed",
    shell:
        "echo 'Analyzed {wildcards.sample}' > {output}  # COMMENT_PLACEHOLDER"


rule summarize:
    input:
        expand("{{rep}}/results/{sample}.analyzed", sample=SAMPLES),
    output:
        "{rep}/results/summary.txt",
    shell:
        """
        echo "Summary of all samples:" > {output}
        for sample in {SAMPLES}; do
            echo "- $sample" >> {output}
        done
        """
